/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE	0x40021000
#define GPIOA_BASE	0x40010800

typedef volatile unsigned long vuint32_t;

typedef union
{
	vuint32_t allBytes;
	struct
	{
		vuint32_t reserved :2;
		vuint32_t IOPAEN :1;
	} bit;
} UAPB2ENR_t;

#define APB2ENR ((volatile UAPB2ENR_t *)(RCC_BASE + 0x18))

typedef union
{
	vuint32_t allBytes;
	struct
	{
		vuint32_t reserved:20;
		vuint32_t mode:4;
	}bit;
} UGPIOACRH_t;

#define GPIOACRH ((volatile UGPIOACRH_t*)(GPIOA_BASE+0x04))

typedef union
{
	vuint32_t allBytes;
	struct
	{
		vuint32_t reserved:13;
		vuint32_t P13:1;
	}bit;
}UGPIOAODR_t;

#define GPIOAODR ((volatile UGPIOAODR_t *)(GPIOA_BASE+0x0c))



int main(void)
{
	/* Loop forever */
	APB2ENR->bit.IOPAEN = 1;
	GPIOACRH->bit.mode = 2;
	while(1)
	{
		long long i;
		GPIOAODR->bit.P13 = 1;
		for(i = 0;i<10000;i++);
		GPIOAODR->bit.P13 = 0;
		for(i = 0;i<10000;i++);
	}

}
